### ISSUE TITLE
Kid you skid

### ISSUE THREAD

**Issue by H4cK3dR4Du** [waltuhium69/Heaven-Nuker#2]
Nice skid buddy
![Screenshot_2023-10-14-16-22-03-144_com mi globalbrowser](https://github.com/waltuhium69/Heaven-Nuker/assets/118562174/8dc8fa6c-59de-410f-a4b5-2245570b553f)
At least change the def names💀💀💀🤡

**Comment by waltuhium69** [comment]
.
